export const data = [
    {
        land: "Thailand",
        breitbandSpeed: 183.58,
        mobileSpeed: 34.4,
        breitbandKosten: 22.15,
        mietkosten: 364.59,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.99,
        lgbt: 5.8100000000000005,
        safetyIndex: 2098,
        temperatur: 27,
        workationScore: 76,
        region: "Asien",
    },
    {
        land: "Dänemark",
        breitbandSpeed: 179.81,
        mobileSpeed: 66.68,
        breitbandKosten: 44.85,
        mietkosten: 1006.58,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.62,
        lgbt: 8.69,
        safetyIndex: 1296,
        temperatur: 9,
        workationScore: 74,
        region: "Europa",
    },
    {
        land: "Rumänien",
        breitbandSpeed: 188.55,
        mobileSpeed: 41.48,
        breitbandKosten: 7.58,
        mietkosten: 347.12,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.14,
        lgbt: 4.1,
        safetyIndex: 1640,
        temperatur: 10,
        workationScore: 73,
        region: "Europa",
    },
    {
        land: "Frankreich",
        breitbandSpeed: 177.93,
        mobileSpeed: 50.45,
        breitbandKosten: 25.86,
        mietkosten: 750.46,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.6899999999999995,
        lgbt: 7.73,
        safetyIndex: 1895,
        temperatur: 12,
        workationScore: 73,
        region: "Europa",
    },
    {
        land: "Ungarn",
        breitbandSpeed: 169.52,
        mobileSpeed: 43.6,
        breitbandKosten: 15.73,
        mietkosten: 387.64,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.99,
        lgbt: 5.08,
        safetyIndex: 1411,
        temperatur: 12,
        workationScore: 73,
        region: "Europa",
    },
    {
        land: "Spanien",
        breitbandSpeed: 160.41,
        mobileSpeed: 41.98,
        breitbandKosten: 36.62,
        mietkosten: 731.45,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.49,
        lgbt: 8.77,
        safetyIndex: 1603,
        temperatur: 14,
        workationScore: 73,
        region: "Europa",
    },
    {
        land: "Niederlande",
        breitbandSpeed: 125.82,
        mobileSpeed: 88.13,
        breitbandKosten: 39.46,
        mietkosten: 1192.24,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.46,
        lgbt: 9.46,
        safetyIndex: 1522,
        temperatur: 10,
        workationScore: 71,
        region: "Europa",
    },
    {
        land: "Deutschland",
        breitbandSpeed: 120.13,
        mobileSpeed: 49.67,
        breitbandKosten: 26.73,
        mietkosten: 867.52,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.16,
        lgbt: 7.73,
        safetyIndex: 1462,
        temperatur: 9,
        workationScore: 70,
        region: "Europa",
    },
    {
        land: "Schweden",
        breitbandSpeed: 158.73,
        mobileSpeed: 56.64,
        breitbandKosten: 36.83,
        mietkosten: 831.69,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.36,
        lgbt: 9.18,
        safetyIndex: 1564,
        temperatur: 3,
        workationScore: 69,
        region: "Europa",
    },
    {
        land: "Neuseeland",
        breitbandSpeed: 139.82,
        mobileSpeed: 61.27,
        breitbandKosten: 50.22,
        mietkosten: 1001.47,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.28,
        lgbt: 8.23,
        safetyIndex: 1269,
        temperatur: 11,
        workationScore: 69,
        region: "Ozeanien",
    },
    {
        land: "Norwegen",
        breitbandSpeed: 146.53,
        mobileSpeed: 87.37,
        breitbandKosten: 66,
        mietkosten: 1026.45,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.39,
        lgbt: 9.38,
        safetyIndex: 1465,
        temperatur: 2,
        workationScore: 69,
        region: "Europa",
    },
    {
        land: "Portugal",
        breitbandSpeed: 131.5,
        mobileSpeed: 87.37,
        breitbandKosten: 45.96,
        mietkosten: 714.98,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.93,
        lgbt: 6.87,
        safetyIndex: 1301,
        temperatur: 16,
        workationScore: 69,
        region: "Europa",
    },
    {
        land: "Kanada",
        breitbandSpeed: 149.35,
        mobileSpeed: 84.54,
        breitbandKosten: 32.42,
        mietkosten: 1150.62,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.1,
        lgbt: 9.02,
        safetyIndex: 1389,
        temperatur: -4,
        workationScore: 68,
        region: "Nordamerika",
    },
    {
        land: "Singapur",
        breitbandSpeed: 229.42,
        mobileSpeed: 64.06,
        breitbandKosten: 40.73,
        mietkosten: 2510.82,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.38,
        lgbt: 5.86,
        safetyIndex: 1326,
        temperatur: 28,
        workationScore: 68,
        region: "Asien",
    },
    {
        land: "Schweiz",
        breitbandSpeed: 186.4,
        mobileSpeed: 73.85,
        breitbandKosten: 67.05,
        mietkosten: 1631.13,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.57,
        lgbt: 8.01,
        safetyIndex: 1357,
        temperatur: 6,
        workationScore: 67,
        region: "Europa",
    },
    {
        land: "Chile",
        breitbandSpeed: 140.23,
        mobileSpeed: 19.21,
        breitbandKosten: 31.61,
        mietkosten: 397.34,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.17,
        lgbt: 6.83,
        safetyIndex: 1840,
        temperatur: 10,
        workationScore: 67,
        region: "Lateinamerika",
    },
    {
        land: "Australien",
        breitbandSpeed: 58.52,
        mobileSpeed: 88.35,
        breitbandKosten: 44.97,
        mietkosten: 1219.24,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.18,
        lgbt: 8.03,
        safetyIndex: 1565,
        temperatur: 22,
        workationScore: 67,
        region: "Ozeanien",
    },
    {
        land: "Brasilien",
        breitbandSpeed: 70.21,
        mobileSpeed: 28.48,
        breitbandKosten: 26.26,
        mietkosten: 285.05,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.33,
        lgbt: 7.22,
        safetyIndex: 2465,
        temperatur: 26,
        workationScore: 67,
        region: "Lateinamerika",
    },
    {
        land: "Malaysia",
        breitbandSpeed: 90.81,
        mobileSpeed: 24.63,
        breitbandKosten: 29.53,
        mietkosten: 332.99,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.38,
        lgbt: 3.48,
        safetyIndex: 1471,
        temperatur: 26,
        workationScore: 67,
        region: "Asien",
    },
    {
        land: "Finnland",
        breitbandSpeed: 108.84,
        mobileSpeed: 53.89,
        breitbandKosten: 40.78,
        mietkosten: 807.89,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.84,
        lgbt: 7.96,
        safetyIndex: 1439,
        temperatur: 2,
        workationScore: 66,
        region: "Europa",
    },
    {
        land: "Japan",
        breitbandSpeed: 139.24,
        mobileSpeed: 38.88,
        breitbandKosten: 37.51,
        mietkosten: 672.41,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.9399999999999995,
        lgbt: 5.26,
        safetyIndex: 1336,
        temperatur: 12,
        workationScore: 66,
        region: "Asien",
    },
    {
        land: "Belgien",
        breitbandSpeed: 97.32,
        mobileSpeed: 58.12,
        breitbandKosten: 41.28,
        mietkosten: 808.78,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.83,
        lgbt: 7.95,
        safetyIndex: 1526,
        temperatur: 10,
        workationScore: 66,
        region: "Europa",
    },
    {
        land: "Litauen",
        breitbandSpeed: 120.89,
        mobileSpeed: 53.39,
        breitbandKosten: 10.36,
        mietkosten: 601.23,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.26,
        lgbt: 4.38,
        safetyIndex: 1724,
        temperatur: 7,
        workationScore: 65,
        region: "Europa",
    },
    {
        land: "Slowenien",
        breitbandSpeed: 86.41,
        mobileSpeed: 45.77,
        breitbandKosten: 28.98,
        mietkosten: 516.06,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.46,
        lgbt: 6.21,
        safetyIndex: 1316,
        temperatur: 10,
        workationScore: 65,
        region: "Europa",
    },
    {
        land: "Tschechien",
        breitbandSpeed: 68.72,
        mobileSpeed: 46.57,
        breitbandKosten: 20.81,
        mietkosten: 647.75,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.97,
        lgbt: 5.87,
        safetyIndex: 1318,
        temperatur: 9,
        workationScore: 65,
        region: "Europa",
    },
    {
        land: "Italien",
        breitbandSpeed: 75.42,
        mobileSpeed: 40.65,
        breitbandKosten: 30.95,
        mietkosten: 654.14,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.48,
        lgbt: 6.9399999999999995,
        safetyIndex: 1643,
        temperatur: 14,
        workationScore: 65,
        region: "Europa",
    },
    {
        land: "Kroatien",
        breitbandSpeed: 47.61,
        mobileSpeed: 66.31,
        breitbandKosten: 31.33,
        mietkosten: 420.87,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.88,
        lgbt: 5.05,
        safetyIndex: 1440,
        temperatur: 12,
        workationScore: 65,
        region: "Europa",
    },
    {
        land: "Vietnam",
        breitbandSpeed: 59.8,
        mobileSpeed: 32.41,
        breitbandKosten: 10.44,
        mietkosten: 341.6,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.41,
        lgbt: 4.99,
        safetyIndex: 1786,
        temperatur: 25,
        workationScore: 65,
        region: "Asien",
    },
    {
        land: "Österreich",
        breitbandSpeed: 74.21,
        mobileSpeed: 55.19,
        breitbandKosten: 33.47,
        mietkosten: 737.63,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.27,
        lgbt: 7.2,
        safetyIndex: 1300,
        temperatur: 7,
        workationScore: 64,
        region: "Europa",
    },
    {
        land: "Polen",
        breitbandSpeed: 111.81,
        mobileSpeed: 37.76,
        breitbandKosten: 14.68,
        mietkosten: 529.46,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.17,
        lgbt: 5.15,
        safetyIndex: 1552,
        temperatur: 9,
        workationScore: 64,
        region: "Europa",
    },
    {
        land: "Costa-Rica",
        breitbandSpeed: 42.44,
        mobileSpeed: 26.42,
        breitbandKosten: 40.19,
        mietkosten: 483.08,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.07,
        lgbt: 6.35,
        safetyIndex: 1732,
        temperatur: 25,
        workationScore: 64,
        region: "Lateinamerika",
    },
    {
        land: "Lettland",
        breitbandSpeed: 115.22,
        mobileSpeed: 33.16,
        breitbandKosten: 15.39,
        mietkosten: 362.85,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.03,
        lgbt: 4.42,
        safetyIndex: 1673,
        temperatur: 7,
        workationScore: 63,
        region: "Europa",
    },
    {
        land: "Malta",
        breitbandSpeed: 115.45,
        mobileSpeed: 42.19,
        breitbandKosten: 37.51,
        mietkosten: 823.73,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.6,
        lgbt: 8.01,
        safetyIndex: 1231,
        temperatur: 20,
        workationScore: 63,
        region: "Europa",
    },
    {
        land: "Slowakei",
        breitbandSpeed: 90.65,
        mobileSpeed: 39.78,
        breitbandKosten: 17.25,
        mietkosten: 507.67,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.33,
        lgbt: 4.82,
        safetyIndex: 1499,
        temperatur: 9,
        workationScore: 63,
        region: "Europa",
    },
    {
        land: "Argentinien",
        breitbandSpeed: 46.39,
        mobileSpeed: 27.93,
        breitbandKosten: 12.73,
        mietkosten: 223.01,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.93,
        lgbt: 7.07,
        safetyIndex: 1911,
        temperatur: 15,
        workationScore: 63,
        region: "Lateinamerika",
    },
    {
        land: "Uruguay",
        breitbandSpeed: 54.87,
        mobileSpeed: 33.42,
        breitbandKosten: 37.29,
        mietkosten: 514.97,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.43,
        lgbt: 7.9,
        safetyIndex: 1795,
        temperatur: 18,
        workationScore: 63,
        region: "Lateinamerika",
    },
    {
        land: "Hong-Kong",
        breitbandSpeed: 215.19,
        mobileSpeed: 56.33,
        breitbandKosten: 44.04,
        mietkosten: 2180.71,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.48,
        lgbt: 6.38,
        safetyIndex: 2010,
        temperatur: 24,
        workationScore: 62,
        region: "Asien",
    },
    {
        land: "Großbritannien",
        breitbandSpeed: 76.49,
        mobileSpeed: 41.72,
        breitbandKosten: 33.21,
        mietkosten: 1025.86,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.06,
        lgbt: 8.34,
        safetyIndex: 1667,
        temperatur: 9,
        workationScore: 62,
        region: "Europa",
    },
    {
        land: "Peru",
        breitbandSpeed: 42.27,
        mobileSpeed: 22.51,
        breitbandKosten: 24.34,
        mietkosten: 358.87,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.84,
        lgbt: 5.15,
        safetyIndex: 2091,
        temperatur: 20,
        workationScore: 62,
        region: "Lateinamerika",
    },
    {
        land: "Indonesien",
        breitbandSpeed: 23.04,
        mobileSpeed: 16.16,
        breitbandKosten: 27.92,
        mietkosten: 255.17,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.35,
        lgbt: 2.79,
        safetyIndex: 1800,
        temperatur: 26,
        workationScore: 62,
        region: "Asien",
    },
    {
        land: "Kolumbien",
        breitbandSpeed: 40.13,
        mobileSpeed: 19.09,
        breitbandKosten: 23.3,
        mietkosten: 227.41,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.01,
        lgbt: 6.1,
        safetyIndex: 2729,
        temperatur: 25,
        workationScore: 61,
        region: "Lateinamerika",
    },
    {
        land: "Estland",
        breitbandSpeed: 74.73,
        mobileSpeed: 48.82,
        breitbandKosten: 26.9,
        mietkosten: 547.46,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.19,
        lgbt: 5.25,
        safetyIndex: 1662,
        temperatur: 6,
        workationScore: 61,
        region: "Europa",
    },
    {
        land: "Mexiko",
        breitbandSpeed: 42.49,
        mobileSpeed: 31.88,
        breitbandKosten: 30.83,
        mietkosten: 461.03,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.32,
        lgbt: 6.5,
        safetyIndex: 2612,
        temperatur: 22,
        workationScore: 61,
        region: "Lateinamerika",
    },
    {
        land: "Griechenland",
        breitbandSpeed: 31.89,
        mobileSpeed: 41.16,
        breitbandKosten: 37.72,
        mietkosten: 393.57,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.72,
        lgbt: 5.44,
        safetyIndex: 1838,
        temperatur: 15,
        workationScore: 60,
        region: "Europa",
    },
    {
        land: "Philippinen",
        breitbandSpeed: 27.07,
        mobileSpeed: 17.83,
        breitbandKosten: 36.54,
        mietkosten: 316.03,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.88,
        lgbt: 6.06,
        safetyIndex: 2339,
        temperatur: 27,
        workationScore: 60,
        region: "Asien",
    },
    {
        land: "Zypern",
        breitbandSpeed: 47.88,
        mobileSpeed: 58.66,
        breitbandKosten: 45.93,
        mietkosten: 800.71,
        workingHolidayVisum: "Ja",
        happinessIndex: 6.22,
        lgbt: 5.16,
        safetyIndex: 1903,
        temperatur: 20,
        workationScore: 60,
        region: "Europa",
    },
    {
        land: "China",
        breitbandSpeed: 140.74,
        mobileSpeed: 124.39,
        breitbandKosten: 29.21,
        mietkosten: 627.23,
        workingHolidayVisum: "Nein",
        happinessIndex: 5.34,
        lgbt: 3.69,
        safetyIndex: 2010,
        temperatur: 8,
        workationScore: 60,
        region: "Asien",
    },
    {
        land: "Israel",
        breitbandSpeed: 113.48,
        mobileSpeed: 23.98,
        breitbandKosten: 18.51,
        mietkosten: 1116.44,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.16,
        lgbt: 5.6899999999999995,
        safetyIndex: 2576,
        temperatur: 21,
        workationScore: 59,
        region: "Mittlerer Osten",
    },
    {
        land: "Irland",
        breitbandSpeed: 93.34,
        mobileSpeed: 30.51,
        breitbandKosten: 53.31,
        mietkosten: 1480.16,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.09,
        lgbt: 8.41,
        safetyIndex: 1288,
        temperatur: 10,
        workationScore: 59,
        region: "Europa",
    },
    {
        land: "Ecuador",
        breitbandSpeed: 27.44,
        mobileSpeed: 21.97,
        breitbandKosten: 40.8,
        mietkosten: 355.82,
        workingHolidayVisum: "Ja",
        happinessIndex: 5.76,
        lgbt: 5.47,
        safetyIndex: 1988,
        temperatur: 21,
        workationScore: 58,
        region: "Lateinamerika",
    },
    {
        land: "Luxemburg",
        breitbandSpeed: 144,
        mobileSpeed: 62.26,
        breitbandKosten: 44.79,
        mietkosten: 1646,
        workingHolidayVisum: "Ja",
        happinessIndex: 7.32,
        lgbt: 7.82,
        safetyIndex: 1357,
        temperatur: 10,
        workationScore: 57,
        region: "Europa",
    },
    {
        land: "Südafrika",
        breitbandSpeed: 37.24,
        mobileSpeed: 38.73,
        breitbandKosten: 41.64,
        mietkosten: 437.98,
        workingHolidayVisum: "Ja",
        happinessIndex: 4.96,
        lgbt: 6.01,
        safetyIndex: 2283,
        temperatur: 18,
        workationScore: 57,
        region: "Afrika",
    },
    {
        land: "Kuwait",
        breitbandSpeed: 110.33,
        mobileSpeed: 58.95,
        breitbandKosten: 45.47,
        mietkosten: 838.64,
        workingHolidayVisum: "Nein",
        happinessIndex: 6.11,
        lgbt: 3.61,
        safetyIndex: 1739,
        temperatur: 28,
        workationScore: 56,
        region: "Mittlerer Osten",
    },
    {
        land: "Bulgarien",
        breitbandSpeed: 67.44,
        mobileSpeed: 77.3,
        breitbandKosten: 14.81,
        mietkosten: 336.3,
        workingHolidayVisum: "Nein",
        happinessIndex: 5.27,
        lgbt: 4.19,
        safetyIndex: 1541,
        temperatur: 12,
        workationScore: 55,
        region: "Europa",
    },
    {
        land: "Saudi-Arabien",
        breitbandSpeed: 75.42,
        mobileSpeed: 84.64,
        breitbandKosten: 77.05,
        mietkosten: 447.78,
        workingHolidayVisum: "Nein",
        happinessIndex: 6.49,
        lgbt: 3.6,
        safetyIndex: 2288,
        temperatur: 27,
        workationScore: 54,
        region: "Mittlerer Osten",
    },
    {
        land: "Trinidad-und-Tobago",
        breitbandSpeed: 68.53,
        mobileSpeed: 41.81,
        breitbandKosten: 52.76,
        mietkosten: 420.54,
        workingHolidayVisum: "Nein",
        happinessIndex: 6.19,
        lgbt: 4.7,
        safetyIndex: 2005,
        temperatur: 27,
        workationScore: 54,
        region: "Lateinamerika",
    },
    {
        land: "Türkei",
        breitbandSpeed: 28.74,
        mobileSpeed: 36.79,
        breitbandKosten: 12.66,
        mietkosten: 249.81,
        workingHolidayVisum: "Ja",
        happinessIndex: 4.95,
        lgbt: 3.94,
        safetyIndex: 2785,
        temperatur: 13,
        workationScore: 54,
        region: "Mittlerer Osten",
    },
    {
        land: "Georgien",
        breitbandSpeed: 26.8,
        mobileSpeed: 32.89,
        breitbandKosten: 12.89,
        mietkosten: 632.05,
        workingHolidayVisum: "Ja",
        happinessIndex: 4.88,
        lgbt: 2.94,
        safetyIndex: 2065,
        temperatur: 10,
        workationScore: 54,
        region: "Europa",
    },
    {
        land: "Panama",
        breitbandSpeed: 99.9,
        mobileSpeed: 17.22,
        breitbandKosten: 44.16,
        mietkosten: 718.83,
        workingHolidayVisum: "Nein",
        happinessIndex: 4.89,
        lgbt: 5.28,
        safetyIndex: 1876,
        temperatur: 26,
        workationScore: 53,
        region: "Lateinamerika",
    },
    {
        land: "Serbien",
        breitbandSpeed: 68.9,
        mobileSpeed: 48.44,
        breitbandKosten: 15.83,
        mietkosten: 341.65,
        workingHolidayVisum: "Nein",
        happinessIndex: 6.18,
        lgbt: 3.71,
        safetyIndex: 1832,
        temperatur: 12,
        workationScore: 52,
        region: "Europa",
    },
];
